### ISSUE TITLE
Necesito que solo se activen los inputs de cada registro

### ISSUE THREAD

**Issue by edmi19944** [HablemosDeVueJS/doctor-vue#11]
Necesito que se activen los input de cada registro.
Tengo un boton editar por cada registro en cada fila de la tabla pero al dar en cualquiera de esto se activan todos los inputs de la tabla 
Y de paso si me pueden dar sugerencias para corregir mi código y que sea más limpio gracias de antemano 

<template>
  <v-app>
  
    <div class="row" style="max-height:fit-content;">
      <div class="col-md-12">
        <button
          type="button"
          style="font-size:12px; float: right; color:white; background-color:#f0ad4e;"
          class="btn btn-warning btn-nuevo"
          v-on:click="nuevoRegistro()"
        >Nuevo</button>
      </div>
      <legend style="margin-left:18px; margin-right:15px">
        <small style="font-size:16px; font-weight:bold">Búsquedas</small>
      </legend>
    </div>
   <label>Buscar</label>
    <input
      type="text"
      class="form-control"
      style="width:150px; height:24px"
      v-model="buscado"
    />
     
        <div v-if="nuevo==true">
      <form method="POST" v-on:submit.prevent="guardarNuevo(registro)">
        <div style="overflow-x: scroll; padding-top:10px; margin-bottom: 40px;">
          <table
          style="table-layout: fixed"
            class="table table-striped table-bordered table-sm"
            id="example"
        
          >
            <thead>
              <tr>
                <th
                  style="width:150px; font-size:12px;"
                  v-for="header in headers"
                  :key="header.value"
                >{{ header.text }}</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <input form="form-ingreso" type="text" class="form-control" v-model="registro.id" />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.i_fiscal_year"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.i_period"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_venta_presupuesto"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_business_unit"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_canal"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_nombre_vendedor"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_bill_source_id"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_entry_type"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.i_modulos"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.n_valor_bruto"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.n_valor_neto"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_bill_by_id"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ec2_categ_catal"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_cod_anunciante"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_nombre_anunciante"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ec2_num_legal"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ec2_family"
                  />
                </td>
                <td>
                  <input class="form-control" type="date" value="registro.d_ec2_fecha_publi" v-model="registro.d_ec2_fecha_publi">
                 
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ec2_producto"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_responsables"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ejecutivos"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_grupo"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_agencia"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_nombre_agencia"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_ec2_prodcont"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_descr_prod_contable"
                  />
                </td>
                <td>
                   <input class="form-control" type="date" value="registro.d_fecha_factura" v-model="registro.d_fecha_factura">
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_close_status"
                  />
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_estado_proceso"
                  />
                </td>
                <td>
                   <input class="form-control" type="date" value="registro.d_dt_fec_crea" v-model="registro.d_dt_fec_crea">
                </td>
                <td>
                  
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_v_usr_crea"
                  />
                </td>
                <td>
                  <input class="form-control" type="date" value="registro.d_dt_fec_mod" v-model="registro.d_dt_fec_mod">
                </td>
                <td>
                  <input
                    form="form-ingreso"
                    type="text"
                    class="form-control"
                    v-model="registro.v_v_usr_mod"
                  />
                </td>
                <td class="td-acciones" style="text-align:center">
                  <button
                    type="submit"
                    style="height:10px font-size: 16px;"
                    class="btn btn-success btn-xs"
                    title="Eliminar"
                    v-on:click="guardarNuevo(registro)"
                  >
                    <span class="mdi mdi-content-save"></span>
                  </button>
                  <button
                    type="submit"
                    style="height:10px font-size: 16px;"
                    class="btn btn-info btn-xs"
                    title="Cancelar"
                    v-on:click="cancelarNuevoRegistro()"
                  >
                    <span class="mdi mdi-cancel"></span>
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </form>
    </div>
    
    <div style="overflow-x: scroll; padding-top:10px;">
      <table class="table table-striped table-bordered table-sm">
        <thead>
          <tr>
            <th
              style="font-size:12px;"
              v-for="header in headers"
              :key="header.value"
            >{{ header.text }}</th>
          </tr>
        </thead>

        <tbody>
          <tr v-for="registro in filtrados" :key="registro.id">
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.id" />
              <p v-else>{{ registro.id }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.i_fiscal_year"
              />
              <p v-else>{{ registro.i_fiscal_year }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.i_period" />
              <p v-else>{{ registro.i_period }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_venta_presupuesto"
              />
              <p v-else>{{ registro.v_venta_presupuesto }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_business_unit"
              />
              <p v-else>{{ registro.v_business_unit }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.v_canal" />
              <p v-else>{{ registro.v_canal }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_nombre_vendedor"
              />
              <p v-else>{{ registro.v_nombre_vendedor }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_bill_source_id"
              />
              <p v-else>{{ registro.v_bill_source_id }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_entry_type"
              />
              <p v-else>{{ registro.v_entry_type}}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.i_modulos" />
              <p v-else>{{ registro.i_modulos }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.n_valor_bruto"
              />
              <p v-else>{{ registro.n_valor_bruto }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.n_valor_neto"
              />
              <p v-else>{{ registro.n_valor_neto }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_bill_by_id"
              />
              <p v-else>{{ registro.v_bill_by_id }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ec2_categ_catal"
              />
              <p v-else>{{ registro.v_ec2_categ_catal }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_cod_anunciante"
              />
              <p v-else>{{ registro.v_cod_anunciante }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_nombre_anunciante"
              />
              <p v-else>{{ registro.v_nombre_anunciante }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ec2_num_legal"
              />
              <p v-else>{{ registro.v_ec2_num_legal }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ec2_family"
              />
              <p v-else>{{ registro.v_ec2_family }}</p>
            </td>
            <td>
               <input v-if="registro.isEditing" class="form-control" type="date" value="registro.d_ec2_fecha_publi" v-model="registro.d_ec2_fecha_publi">
              <p v-else>{{ registro.d_ec2_fecha_publi }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ec2_producto"
              />
              <p v-else>{{ registro.v_ec2_producto }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_responsables"
              />
              <p v-else>{{ registro.v_responsables }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ejecutivos"
              />
              <p v-else>{{ registro.v_ejecutivos }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.v_grupo" />
              <p v-else>{{ registro.v_grupo }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" type="text" class="form-control" v-model="registro.v_agencia" />
              <p v-else>{{ registro.v_agencia }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_nombre_agencia"
              />
              <p v-else>{{ registro.v_nombre_agencia }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_ec2_prodcont"
              />
              <p v-else>{{ registro.v_ec2_prodcont }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_descr_prod_contable"
              />
              <p v-else>{{ registro.v_descr_prod_contable }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" class="form-control" type="date" value="registro.d_fecha_factura" v-model="registro.d_fecha_factura">
              <p v-else>{{ registro.d_fecha_factura }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_close_status"
              />
              <p v-else>{{ registro.v_close_status }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_estado_proceso"
              />
              <p v-else>{{ registro.v_estado_proceso }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" class="form-control" type="date" value="registro.d_dt_fec_crea" v-model="registro.d_dt_fec_crea">

              <p v-else>{{ registro.d_dt_fec_crea }}</p>
            </td>
            <td>
              <input
                v-if="regitro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_v_usr_crea"
              />
              <p v-else>{{ registro.v_v_usr_crea }}</p>
            </td>
            <td>
              <input v-if="registro.isEditing" class="form-control" type="date" value="registro.d_dt_fec_mod" v-model="registro.d_dt_fec_mod">
              <p v-else>{{ registro.d_dt_fec_mod }}</p>
            </td>
            <td>
              <input
                v-if="registro.isEditing"
                type="text"
                class="form-control"
                v-model="registro.v_v_usr_mod"
              />
              <p v-else>{{ registro.v_v_usr_mod }}</p>
            </td>
            <td class="td-acciones" style="text-align:center">
              <button
                type="button"
                style="display:block; float:left; height:10px font-size: 16px;"
                class="btn btn-success btn-xs"
                title="Guardar"
                v-on:click="actualizarRegistro(registro)"
                v-if="editMode"
              >
                <span class="mdi mdi-content-save"></span>
              </button>

              <button
                type="button"
                style="display:block; float: left; height:10px font-size: 16px;"
                class="btn btn-primary btn-xs"
                title="Editar"
                v-on:click="editarRegistro(registro)"
                v-else
              >
                <span class="mdi mdi-pencil"></span>
              </button>

              <button
                type="button"
                style="display: inline; height:10px font-size: 16px;"
                class="btn btn-danger btn-xs"
                title="Eliminar"
                v-on:click="eliminarRegistro(registro)"
              >
                <span style="color:white;" class="mdi mdi-delete"></span>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </v-app>
</template>

<script>
import $ from "jquery";
import datables from "datatables.net";
export default {
  data: () => ({
    offset: 3,
    buscado: "",
    nuevo: "false",
    editMode: false,
    registros: [],
    error: [],
    errors:'',
    registro: {
      i_fiscal_year: "",
      i_period: "",
      v_venta_presupuesto: "",
      v_business_unit: "",
      v_canal: "",
      v_nombre_vendedor: "",
      v_bill_source_id: "",
      v_entry_type: "",
      i_modulos: "",
      n_valor_bruto: "",
      n_valor_neto: "",
      v_bill_by_id: "",
      v_ec2_cate_catal: "",
      v_cod_anunciante: "",
      v_nombre_anunciante: "",
      v_ec2_num_legal: "",
      v_ec2_family: "",
      d_ec2_fecha_publi: "",
      v_ec2_producto: "",
      v_responsables: "",
      v_ejecutivos: "",
      v_grupo: "",
      v_agencia: "",
      v_nombre_agencia: "",
      v_ec2_prodcont: "",
      v_descr_prod_contable: "",
      d_fecha_factura: "",
      v_close_status: "",
      v_estado_proceso: "",
      d_dt_fec_crea: "",
      v_v_usr_crea: "",
      d_dt_fec_mod: "",
      v_v_usr_mod: ""
    },
    headers: [
      { text: "ID", align: "start", value: "id" },
      { text: "Año Fiscal", align: "start", value: "i_fiscal_year" },
      { text: "Periodo", value: "i_period" },
      { text: "Venta Presupuesto", value: "v_venta_presupuesto" },
      { text: "Unidad de Negocio", value: "v_business_unit" },
      { text: "Canal", value: "v_canal" },
      { text: "Nombre Vendedor", value: "v_nombre_vendedor" },
      { text: "Bill Source Id", value: "v_bill_source_id" },
      { text: "Entry Type", value: "v_entry_type" },
      { text: "Módulos", value: "i_modulos" },
      { text: "Valor Bruto", value: "n_valor_bruto" },
      { text: "Valor Neto", value: "n_valor_neto" },
      { text: "Bill By Id", value: "v_bill_by_id" },
      { text: "Ec2 Categ Catal", value: "v_ec2_categ_catal" },
      { text: "Cod Anunciante", value: "v_cod_anunciante" },
      { text: "Nombre Anunciante", value: "v_nombre_anunciante" },
      { text: "Ec2 Num Legal", value: "v_ec2_num_legal" },
      { text: "Ec2 Family", value: "v_ec2_family" },
      { text: "D Ec2 Fecha Publicación", value: "d_ec2_fecha_publi" },
      { text: "Ec2 Producto", value: "v_ec2_producto" },
      { text: "Responsables", value: "v_responsables" },
      { text: "Ejecutivos", value: "v_ejecutivos" },
      { text: "Grupo", value: "v_grupo" },
      { text: "Agencia", value: "v_agencia" },
      { text: "Nombre Agencia", value: "v_nombre_agencia" },
      { text: "Ec2 Prodcont", value: "v_ec2_prodcont" },
      { text: "Descr Prod Contable", value: "v_descr_prod_contable" },
      { text: "Fecha Factura", value: "d_fecha_factura" },
      { text: "Close Status", value: "v_close_status" },
      { text: "Estado Proceso", value: "v_estado_proceso" },
      { text: "Dt Fec Crea", value: "d_dt_fec_crea" },
      { text: "V Usr Crea", value: "v_v_usr_crea" },
      { text: "Dt Fec Mod", value: "d_dt_fec_mod" },
      { text: "V Usr Mod", value: "v_v_usr_mod" },
      { text: "Acciones", value: "actions", sorteable: false }
    ]
  }),
  created() {
    this.listarRegistros();
  },
  methods: {
    cancelarNuevoRegistro() {
      this.nuevo = false;
    },
    nuevoRegistro: function() {
      this.nuevo = true;
  
    },
    listarRegistros: function() {
      axios
        .get("backend/consultas/actuaria")
        .then(response => {
          this.registros = response.data;
          console.log("HOla");
        })

        .catch(error => {
          console.log(error.response);
        });
    },
    eliminarRegistro: function(registro) {
      const index = this.registros.indexOf(registro);
      axios
        .post(`backend/consultas/actuaria/eliminar/${registro.id}`)
        .then(() => {
          this.registros.splice(index, 1);
        });
    },
    editarRegistro: function(registro) {
      //this.editMode = true;
      this.registro.isEditing=true;
    },
    actualizarRegistro: function(registro) {
      const parametros = {
        i_fiscal_year: registro.i_fiscal_year,
        i_period: registro.i_period,
        v_venta_presupuesto: registro.v_venta_presupuesto,
        v_business_unit: registro.v_business_unit,
        v_canal: registro.v_canal,
        v_nombre_vendedor: registro.v_nombre_vendedor,
        v_bill_source_id: registro.v_bill_source_id,
        v_entry_type: registro.v_entry_type,
        i_modulos: registro.i_modulos,
        n_valor_bruto: registro.n_valor_bruto,
        n_valor_neto: registro.n_valor_neto,
        v_bill_by_id: registro.v_bill_by_id,
        v_ec2_cate_catal: registro.v_ec2_categ_catal,
        v_cod_anunciante: registro.v_cod_anunciante,
        v_nombre_anunciante: registro.v_nombre_anunciante,
        v_ec2_num_legal: registro.v_ec2_num_legal,
        v_ec2_family: registro.v_ec2_family,
        d_ec2_fecha_publi: registro.d_ec2_fecha_publi,
        v_ec2_producto: registro.v_ec2_producto,
        v_responsables: registro.v_responsables,
        v_ejecutivos: registro.v_ejecutivos,
        v_grupo: registro.v_grupo,
        v_agencia: registro.v_agencia,
        v_nombre_agencia: registro.v_nombre_agencia,
        v_ec2_prodcont: registro.v_ec2_prodcont,
        v_descr_prod_contable: registro.v_descr_prod_contable,
        d_fecha_factura: registro.d_fecha_factura,
        v_close_status: registro.v_close_status,
        v_estado_proceso: registro.v_estado_proceso,
        d_dt_fec_crea: registro.d_dt_fec_crea,
        v_v_usr_crea: registro.v_v_usr_crea,
        d_dt_fec_mod: registro.d_dt_fec_mod,
        v_v_usr_mod: registro.v_v_usr_mod
      };
      axios
        .post(
          `backend/consultas/actuaria/actualizar/${registro.id}`,
          parametros
        )
        .then(res => {
          this.editMode = false;
          const index = this.registros.indexOf(registro);
          this.registros[index] = registro;
        });
    },
    verificarCamposVacios: function(){
            if(this.registro.i_fiscal_year.trim()==''||
        this.registro.i_period.trim()==''
        ||  this.registro.v_venta_presupuesto.trim()==''
        ||  this.registro.v_business_unit.trim()==''
        ||  this.registro.v_canal.trim()==''
        ||  this.registro.v_nombre_vendedor.trim()==''
        ||  this.registro.v_bill_source_id.trim()==''
        ||  this.registro.v_entry_type.trim()==''
        ||  this.registro.i_modulos.trim()==''
        ||  this.registro.n_valor_bruto.trim()==''
        ||  this.registro.n_valor_neto.trim()==''
        ||  this.registro.v_bill_by_id.trim()==''
        ||  this.registro.v_ec2_categ_catal.trim()==''
        ||  this.registro.v_cod_anunciante.trim()==''
        ||  this.registro.v_nombre_anunciante.trim()==''
        ||  this.registro.v_ec2_num_legal.trim()==''
        ||  this.registro.v_ec2_family.trim()==''
        ||  this.registro.d_ec2_fecha_publi.trim()==''
        ||  this.registro.v_ec2_producto.trim()==''
        ||  this.registro.v_responsables.trim()==''
        ||  this.registro.v_ejecutivos.trim()==''
        ||  this.registro.v_grupo.trim()==''
        ||  this.registro.v_agencia.trim()==''
        ||  this.registro.v_nombre_agencia.trim()==''
        ||  this.registro.v_ec2_prodcont.trim()==''
        ||  this.registro.v_descr_prod_contable.trim()==''
        ||  this.registro.d_fecha_factura.trim()==''
        ||  this.registro.v_close_status.trim()==''
        ||  this.registro.v_estado_proceso.trim()==''
        ||  this.registro.d_dt_fec_crea.trim()==''
        ||  this.registro.v_v_usr_crea.trim()==''
        ||  this.registro.d_dt_fec_mod.trim()==''
        ||  this.registro.v_v_usr_mod.trim()==''
        ){
        alert("Llene todos los campos");
        return 0;
      }
      else
        return 1;
    },
    guardarNuevo: function(registro) {
      if(this.verificarCamposVacios()==0){
        return;
      } 
      axios
        .post("backend/consultas/actuaria/store", this.registro)
        .then(res => {
          console.log("funciona");
              this.registros.push(this.registro)
          this.nuevo=false;
          this.registro= {
      i_fiscal_year: "",
      i_period: "",
      v_venta_presupuesto: "",
      v_business_unit: "",
      v_canal: "",
      v_nombre_vendedor: "",
      v_bill_source_id: "",
      v_entry_type: "",
      i_modulos: "",
      n_valor_bruto: "",
      n_valor_neto: "",
      v_bill_by_id: "",
      v_ec2_cate_catal: "",
      v_cod_anunciante: "",
      v_nombre_anunciante: "",
      v_ec2_num_legal: "",
      v_ec2_family: "",
      d_ec2_fecha_publi: "",
      v_ec2_producto: "",
      v_responsables: "",
      v_ejecutivos: "",
      v_grupo: "",
      v_agencia: "",
      v_nombre_agencia: "",
      v_ec2_prodcont: "",
      v_descr_prod_contable: "",
      d_fecha_factura: "",
      v_close_status: "",
      v_estado_proceso: "",
      d_dt_fec_crea: "",
      v_v_usr_crea: "",
      d_dt_fec_mod: "",
      v_v_usr_mod: ""
    }
        })
        .catch(error => {
          
          this.errors = error.response.data;
          console.log(this.errors);
        });
    },
  },
  computed: {
    filtrados: function() {
      return this.registros.filter(registro => {
        return (
          registro.i_fiscal_year.toLowerCase().includes(this.buscado.toLowerCase()) ||
          registro.i_period.toLowerCase().includes(this.buscado.toLowerCase()) || 
          registro.i_modulos.toLowerCase().includes(this.buscado.toLowerCase())|| 
          registro.n_valor_bruto.toLowerCase().includes(this.buscado.toLowerCase())|| 
          registro.n_valor_neto.toLowerCase().includes(this.buscado.toLowerCase())
          || registro.v_venta_presupuesto.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_business_unit.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_canal.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_nombre_vendedor.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_bill_source_id.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_entry_type.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_bill_by_id.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_cod_anunciante.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_nombre_anunciante.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_num_legal.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_categ_catal.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_cod_anunciante.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_nombre_anunciante.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_num_legal.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.d_dt_fec_crea.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.d_dt_fec_mod.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.d_fecha_factura.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.d_ec2_fecha_publi.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_family.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_producto.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_responsables.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ejecutivos.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_grupo.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_agencia.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_nombre_agencia.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_ec2_prodcont.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_descr_prod_contable.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_close_status.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_estado_proceso.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_v_usr_crea.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
          || registro.v_v_usr_mod.toString().toLowerCase().includes(this.buscado.toLowerCase().toString())
        );
      });
    }
  }
};
</script>

**Comment by ochaminho** [comment]
Problemas de implementación por código repetido, se refactorizó para que pudiese ser solventado.
