### ISSUE TITLE
Al compilar sale error "TypeError: Cannot read property '_normalized' of undefined"

### ISSUE THREAD

**Issue by maritogaleano** [HablemosDeVueJS/doctor-vue#6]
Este es el código del main.js

`import Vue from 'vue';
import VueRouter from 'vue-router';
import Home from '../views/Home.vue';

Vue.use(VueRouter);

const routes = [
  {
    path: '/',
    name: 'home',
    component: Home,
  },
  {
    path: '/about',
    name: 'about',
    // route level code-splitting
    // this generates a separate chunk (about.[hash].js) for this route
    // which is lazy-loaded when the route is visited.
    component: () => import(/* webpackChunkName: "about" */ '../views/About.vue'),
  },
];

const router = new VueRouter({
  routes,
});

export default router;`

**Comment by aRendonC** [comment]
@maritogaleano Lo ideal sería que colocaras también el error que te sale para tener una mejor referencia.
